### ISSUE TITLE
로그인 및 회원가입 기능구현 계획

### ISSUE THREAD

**Issue by blackdemon129** [venture-project-database/SahmYookVegas#7]
## 작성자
김태영

## 맡은 파트
로그인 및 회원가입

## 구현할 기능
- 프로그램을 시작했을 때 1. 로그인 2. 회원가입이 나오고
- 로그인을 선택하면 아이디와 비밀번호를 치고 앱에 접속 할 수 있다.
- 회원가입을 선택하면 아이디와 비밀번호, 이름과 전화번호를 입력할 수 있다.
- 아이디는 중복될 수 없으며, 중복되는 아이디가 있다면 경고문이 발생하며 중복되지 않는 아이디를 입력해야 한다.
- 아이디와 비밀번호, 이름과 전화번호는 데이터베이스에 저장되어 로그인을 했을 시에 내 정보를 확인 할 수 있다.  

## 기능 문서화 (상황에 따라 커스텀)
==================================================================
- 회원가입을 할 경우 데이터베이스에 customer_id, customer_pw, customer_name, customer_phone 에 데이터가 저장된다. 
- 로그인을 할 경우 메인 화면이 나오며 개인 정보를 조회하거나 상품 구매, 칩 구매, 현금 충전 및 게임 등의 기능을 이용할 수 있다.

**Comment by GTU9** [comment]
기능 문서화에 로그인 기능도 적어주세요

**Comment by blackdemon129** [comment]
@GTU9 넵 확인하고 추가했습니다!

**Comment by blackdemon129** [comment]
로그인 및 회원가입 기본 토대 완성입니다. #18

**Comment by blackdemon129** [comment]
로그인 및 회원가입 창 뜰 때, 숫자 뿐만 아니라 다른 문자를 입력해도 오류가 뜨지 않고 다시 로그인 창으로 돌아가게 수정했습니다. #24

**Comment by blackdemon129** [comment]
로그인 이후 메인 화면에 각종 메뉴들, 그리고 로그아웃 기능까지 구현 완료 했습니다! #25 #26
