### ISSUE TITLE
chip 반환 기능 구현

### ISSUE THREAD

**Issue by k168ww** [venture-project-database/SahmYookVegas#8]
## 작성자
> 심선우

## 맡은 파트
> Chip 교환 및 반환 기능 구현

## 구현할 기능
> 가지고 있는 칩을 지갑의 잔액으로 반환하는 기능을 구현
> (반환된 돈의 액수를 로그로 저장)

기능 문서화 (상황에 따라 커스텀)
==================================================================

SQL: 사용자가 입력한 돈과 각 칩의 개수를 토대로 실제 반환 과정을 처리한다.
뷰 테이블 출력: 반환한 칩의 종류와 개수를 출력한다. 입력한 칩의 개수에 따라 반환된 돈의 액수가 결정된다.

**Comment by GTU9** [comment]
main Application에는 왠만하면 코드는 작성 해주지 말고 다른 실행문을 다른 클래스로 만들어주세요

**Comment by k168ww** [comment]
common 패키지의 Application이 아닌 chip 패키지에 실행용으로 만들어본건데 이렇게 하지 말라는 말씀이신가요??

**Comment by GTU9** [comment]
예 맞습니다. @k168ww
