### ISSUE TITLE
지갑 충전 및 상품 구매 기능 구현 계획

### ISSUE THREAD

**Issue by moressangplease** [venture-project-database/SahmYookVegas#9]
## 작성자
> 김민수

## 맡은 파트
> 지갑 충전 및 상품 구매

## 구현할 기능
> 원하는 금액만큼 돈 충전 후 충전 금액에 따라 크레딧을 적립
> 지갑에 있는 돈과 크레딧 중 원하는 방법으로 카지노 내에서 상품을 구매

## 기능 문서화 (상황에 따라 커스텀)
==================================================================
>고객이 지갑에 돈을 충전한 후 금액에 따라 크레딧이 자동으로 적립되고, 충전 금액은 customer 테이블의 balance에, 크레딧은 credit에 저장된다. (UPDATE)
> 원하는 방법을 선택해서 상품을 구매하고 금액만큼 지갑 잔액이나 크레딧 잔액을 차감시킨다.

**Comment by GTU9** [comment]
구현 완료되시면 커밋 메세지에  이슈 번호 (#)태그 붙여주세요
